# Generated by Django 4.2.6 on 2024-01-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestauranteWT', '0002_remove_ingrediente_stock_disponible_wt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo',
            name='imagen_wt',
        ),
        migrations.AddField(
            model_name='tipo',
            name='calorias_wt',
            field=models.IntegerField(default=0),
        ),
    ]
