# Generated by Django 4.2.6 on 2024-01-12 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestauranteWT', '0003_remove_tipo_imagen_wt_tipo_calorias_wt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='id_wt',
            new_name='idCliente_wt',
        ),
        migrations.RenameField(
            model_name='detalle',
            old_name='id_wt',
            new_name='idDetalle_wt',
        ),
        migrations.RenameField(
            model_name='ingrediente',
            old_name='id_wt',
            new_name='idIngrediente_wt',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='id_wt',
            new_name='idPedido_wt',
        ),
        migrations.RenameField(
            model_name='platillo',
            old_name='id_wt',
            new_name='idPlatillo_wt',
        ),
        migrations.RenameField(
            model_name='provincia',
            old_name='id_wt',
            new_name='idProvincia_wt',
        ),
        migrations.RenameField(
            model_name='receta',
            old_name='id_wt',
            new_name='idReceta_wt',
        ),
        migrations.RenameField(
            model_name='tipo',
            old_name='id_wt',
            new_name='idTipo_wt',
        ),
    ]
