# Generated by Django 4.2.6 on 2024-01-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestauranteWT', '0005_alter_cliente_idcliente_wt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='nombre_wt',
            field=models.CharField(max_length=200),
        ),
    ]
