# Generated by Django 4.2.6 on 2024-01-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestauranteWT', '0006_alter_ingrediente_nombre_wt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillo',
            name='nombre_wt',
            field=models.CharField(max_length=200),
        ),
    ]
