# Generated by Django 4.2.6 on 2024-01-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestauranteWT', '0008_alter_cliente_provincia_wt_alter_detalle_pedido_wt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_wt',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago_wt',
            field=models.CharField(max_length=30),
        ),
    ]
