# Generated by Django 4.2.6 on 2024-01-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestauranteWT', '0009_alter_pedido_estado_wt_alter_pedido_metodo_pago_wt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle',
            name='platillo_wt',
        ),
    ]
