# Generated by Django 4.2.6 on 2024-01-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestauranteWT', '0012_rename_platillod_wt_detalle_platillo_wt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle',
            old_name='platillo_wt',
            new_name='platilloD_wt',
        ),
    ]
