# Generated by Django 4.2.6 on 2024-01-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestauranteWT', '0013_rename_platillo_wt_detalle_platillod_wt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillo',
            name='descripcion_wt',
            field=models.CharField(max_length=110),
        ),
    ]
