# Generated by Django 4.2.6 on 2024-01-14 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestauranteWT', '0014_alter_platillo_descripcion_wt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle',
            old_name='platilloD_wt',
            new_name='platillo_wt',
        ),
    ]
